spring:
  config:
    import:
      - service-properties.yaml
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
server:
  port: ${PORT}
eureka:
  instance:
    non-secure-port: ${PORT}