spring:
  application:
    name: projects
  datasource:
    url: ${JDBC_URL}
    username: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
server:
  port: 0
eureka:
  instance:
    non-secure-port: 0
    instance-id: ${spring.application.name}:${random.value}
greeting: Default greeting